### ISSUE TITLE
eslint-config-prettier (>= 8.0.0) is not working

### ISSUE THREAD

**Issue by dachi023** [Connehito/eslint-config-connehito#101]
```
$ yarn run eslint src/

Oops! Something went wrong! :(

ESLint: 7.22.0

Error: Cannot read config file: /Users/.../node_modules/eslint-config-prettier/@typescript-eslint.js
Error: "prettier/@typescript-eslint" has been merged into "prettier" in eslint-config-prettier 8.0.0. See: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21
```

**Comment by smarttin** [comment]
refer to this change log to fix this
[](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-810-2021-02-24)

**Comment by dachi023** [comment]
@smarttin 
Thank you for the information!
This issue has already been addressed and should have been closed.

https://github.com/Connehito/eslint-config-connehito/commit/0eb5b283453479e8c2390f96b100cc8a81bf3a82
